### model
# model_name_or_path: /gammadisk/shared_data/models/Qwen__Qwen2.5-Math-7B-Instruct
model_name_or_path: /data/kris/shared_data/models/Llama-3.2-3B  
# output_dir: /data/kris/qianxuzhen/Pruning-LLMs/LLaMA-Factory/saves/meta-llama__Llama-3.2-1B-Instruct-tap0.9-learnable-interm/lora/sft/max_samples_2M
output_dir: /data/kris/qianxuzhen/Pruning-LLMs/LLaMA-Factory/saves/meta-llama__Llama-3.2-3B-tap0.9-learnable-interm/lora/sft/max_samples_zipf_dummy_1M_alpha_0.005_T_4

# tap args
tap_enabled: true
# tap_enabled: false
tap_rank: 512
tap_stop_at_steps: 9000 
tap_remain_ratio: 0.9
tap_learnable_mask: true
# tap_dpo_loss: true


max_samples: 1000000
num_train_epochs: 2.0


trust_remote_code: true
flash_attn: fa2

# disable_gradient_checkpointing: true
# use_unsloth: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: nvidia__OpenMathInstruct-2
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 8

### output
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train  
per_device_train_batch_size: 7
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
# learning_rate: 2.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
